import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        "text-display-1-regular",
        "text-display-1-medium",
        "text-display-1-bold",
        "text-display-2-regular",
        "text-display-2-medium",
        "text-display-2-bold",
        "text-display-3-regular",
        "text-display-3-medium",
        "text-display-3-bold",
        "text-title-1-regular",
        "text-title-1-medium",
        "text-title-1-bold",
        "text-title-2-regular",
        "text-title-2-medium",
        "text-title-2-bold",
        "text-title-3-regular",
        "text-title-3-medium",
        "text-title-3-bold",
        "text-heading-1-regular",
        "text-heading-1-medium",
        "text-heading-1-bold",
        "text-heading-2-regular",
        "text-heading-2-medium",
        "text-heading-2-bold",
        "text-headline-1-regular",
        "text-headline-1-medium",
        "text-headline-1-bold",
        "text-headline-2-regular",
        "text-headline-2-medium",
        "text-headline-2-bold",
        "text-body-1-normal-regular",
        "text-body-1-normal-medium",
        "text-body-1-normal-bold",
        "text-body-1-reading-regular",
        "text-body-1-reading-medium",
        "text-body-1-reading-bold",
        "text-body-2-normal-regular",
        "text-body-2-normal-medium",
        "text-body-2-normal-bold",
        "text-body-2-reading-regular",
        "text-body-2-reading-medium",
        "text-body-2-reading-bold",
        "text-label-1-normal-regular",
        "text-label-1-normal-medium",
        "text-label-1-normal-bold",
        "text-label-1-reading-regular",
        "text-label-1-reading-medium",
        "text-label-1-reading-bold",
        "text-label-2-regular",
        "text-label-2-medium",
        "text-label-2-bold",
        "text-caption-1-regular",
        "text-caption-1-medium",
        "text-caption-1-bold",
        "text-caption-2-regular",
        "text-caption-2-medium",
        "text-caption-2-bold",
      ],
      "text-color": [
        "text-label-normal",
        "text-label-strong",
        "text-label-alternative",
        "text-label-neutral",
        "text-label-assistive",
        "text-label-disable",

        "text-primary-normal",
        "text-primary-strong",
        "text-primary-heavy",

        "text-status-positive",
        "text-status-cautionary",
        "text-status-negative",

        "text-static-white",
        "text-static-black",

        "text-inverse-primary",
        "text-inverse-background",
        "text-inverse-label",

        "text-accent-fg-red",
        "text-accent-fg-red-orange",
        "text-accent-fg-orange",
        "text-accent-fg-lime",
        "text-accent-fg-green",
        "text-accent-fg-cyan",
        "text-accent-fg-light-blue",
        "text-accent-fg-blue",
        "text-accent-fg-violet",
        "text-accent-fg-purple",
        "text-accent-fg-pink",
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
