declare global {
  type BLOCK_LIST = (
    | CAREER_BLOCK_ITEM
    | PROJECT_BLOCK_ITEM
    | SKILL_BLOCK_ITEM
    | INTRODUCTION_BLOCK_ITEM
    | SUMMARY_BLOCK_ITEM
    | EDUCATION_BLOCK_ITEM
    | CERTIFICATE_BLOCK_ITEM
    | ACTIVITY_BLOCK_ITEM
    | BASIC_INFO_BLOCK_ITEM
  )[];

  type API_CLIENT_BLOCKS_LIST = BLOCK_LIST;

  type API_SERVER_BLOCKS_LIST = RESPONSE_MODEL<BLOCK_LIST>;
}

export {};
