/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/oauth2/authorization/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Google 소셜 로그인
     * @description 브라우저를 이 URL로 이동시킵니다 (`window.location.href = ...`).
     *
     *     로그인 성공 후 프론트엔드 URL로 리다이렉트되며 `access_token`(1h), `refresh_token`(7d) 쿠키가 자동 설정됩니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Google 인증 서버로 리다이렉트 */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description OAUTH2_PROVIDER_ERROR — 소셜 로그인 제공자 오류 */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth2/authorization/kakao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kakao 소셜 로그인
     * @description 브라우저를 이 URL로 이동시킵니다 (`window.location.href = ...`).
     *
     *     로그인 성공 후 프론트엔드 URL로 리다이렉트되며 `access_token`(1h), `refresh_token`(7d) 쿠키가 자동 설정됩니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Kakao 인증 서버로 리다이렉트 */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description OAUTH2_PROVIDER_ERROR — 소셜 로그인 제공자 오류 */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth2/authorization/naver": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Naver 소셜 로그인
     * @description 브라우저를 이 URL로 이동시킵니다 (`window.location.href = ...`).
     *
     *     로그인 성공 후 프론트엔드 URL로 리다이렉트되며 `access_token`(1h), `refresh_token`(7d) 쿠키가 자동 설정됩니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Naver 인증 서버로 리다이렉트 */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description OAUTH2_PROVIDER_ERROR — 소셜 로그인 제공자 오류 */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/blocks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 블록 수정
     * @description 블록의 제목과 내용을 수정합니다. 본인 소유 블록만 수정 가능합니다.
     */
    put: operations["updateBlock"];
    post?: never;
    /**
     * 블록 삭제
     * @description 블록을 소프트 삭제합니다. 본인 소유 블록만 삭제 가능합니다.
     */
    delete: operations["deleteBlock"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/blocks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 블록 목록 조회
     * @description 로그인한 사용자의 블록 목록을 반환합니다. `type` 파라미터를 지정하면 해당 타입만 필터링합니다.
     */
    get: operations["getBlocks"];
    put?: never;
    /**
     * 블록 생성
     * @description 새로운 블록을 생성합니다. `contentJson`은 블록 타입에 맞는 JSON 문자열을 그대로 전달합니다.
     */
    post: operations["createBlock"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Access Token 갱신
     * @description refresh_token 쿠키를 사용해 새로운 access_token 쿠키를 발급합니다.
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description access_token을 Redis Blacklist에 등록하고 Refresh Token을 삭제합니다. 쿠키를 만료시킵니다.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description access_token 쿠키를 기반으로 현재 로그인한 사용자 정보를 반환합니다.
     */
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/withdraw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 회원 탈퇴
     * @description 즉시 계정을 비활성화하고 30일 후 영구 삭제합니다. 유예기간 내 재로그인 시 복구됩니다.
     */
    delete: operations["withdraw"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /** @example false */
      success?: unknown;
      /** @example 에러 메시지 */
      message?: unknown;
    };
    /** @description 블록 수정 요청 */
    UpdateBlockRequest: {
      /**
       * @description 블록 제목 (최대 200자)
       * @example 수정된 제목
       */
      title: string;
      /**
       * @description 블록 내용을 JSON 문자열로 직렬화하여 전달 (오브젝트 아님). 예: {"company":"카카오","startDate":"2024-01"}
       * @example {}
       */
      contentJson: string;
    };
    ApiResponseBlockResponse: {
      success: boolean;
      data?: components["schemas"]["BlockResponse"];
      message?: string;
    };
    /** @description 블록 응답 */
    BlockResponse: {
      /**
       * Format: int64
       * @description 블록 ID
       * @example 1
       */
      id: number;
      /**
       * @description 블록 타입
       * @example CAREER
       * @enum {string}
       */
      type:
        | "CAREER"
        | "SKILL"
        | "PROJECT"
        | "EDUCATION"
        | "CERTIFICATE"
        | "ACTIVITY"
        | "CUSTOM";
      /**
       * @description 블록 제목
       * @example 카카오 백엔드 개발자
       */
      title: string;
      /**
       * @description 블록 내용 JSON 문자열
       * @example {}
       */
      contentJson: string;
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2026-05-11T10:00:00
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 수정 일시
       * @example 2026-05-11T10:00:00
       */
      updatedAt: string;
    };
    /** @description 블록 생성 요청 */
    CreateBlockRequest: {
      /**
       * @description 블록 타입
       * @example CAREER
       * @enum {string}
       */
      type:
        | "CAREER"
        | "SKILL"
        | "PROJECT"
        | "EDUCATION"
        | "CERTIFICATE"
        | "ACTIVITY"
        | "CUSTOM";
      /**
       * @description 블록 제목 (최대 200자)
       * @example 카카오 백엔드 개발자
       */
      title: string;
      /**
       * @description 블록 내용을 JSON 문자열로 직렬화하여 전달 (오브젝트 아님). 예: {"company":"카카오","startDate":"2024-01"}
       * @example {}
       */
      contentJson: string;
    };
    ApiResponse: {
      success: boolean;
      data?: unknown;
      message?: string;
    };
    ApiResponseListBlockResponse: {
      success: boolean;
      data?: components["schemas"]["BlockResponse"][];
      message?: string;
    };
    /** @description 내 정보 응답 */
    UserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      id: number;
      /**
       * @description 이메일
       * @example user@example.com
       */
      email: string;
      /**
       * @description 이름
       * @example 홍길동
       */
      name: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/profile.jpg
       */
      profileImageUrl?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  updateBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBlockRequest"];
      };
    };
    responses: {
      /** @description 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBlockResponse"];
        };
      };
      /** @description 입력값 유효성 검증 실패 (VALIDATION_FAILED) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "입력값이 올바르지 않습니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 본인 소유가 아닌 블록 수정 시도 (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "접근 권한이 없습니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 블록을 찾을 수 없음 (RESOURCE_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "블록을 찾을 수 없습니다."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 본인 소유가 아닌 블록 삭제 시도 (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "접근 권한이 없습니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 블록을 찾을 수 없음 (RESOURCE_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "블록을 찾을 수 없습니다."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getBlocks: {
    parameters: {
      query?: {
        type?:
          | "CAREER"
          | "SKILL"
          | "PROJECT"
          | "EDUCATION"
          | "CERTIFICATE"
          | "ACTIVITY"
          | "CUSTOM";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseListBlockResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createBlock: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBlockRequest"];
      };
    };
    responses: {
      /** @description 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBlockResponse"];
        };
      };
      /** @description 입력값 유효성 검증 실패 (VALIDATION_FAILED) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "입력값이 올바르지 않습니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 토큰 갱신 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponse"];
        };
      };
      /** @description refresh_token 쿠키 없음 또는 만료 (UNAUTHORIZED / TOKEN_EXPIRED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 로그아웃 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponse"];
        };
      };
      /** @description access_token 쿠키 없음 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 사용자를 찾을 수 없음 (RESOURCE_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "사용자를 찾을 수 없습니다."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query: {
        provider: "GOOGLE" | "KAKAO" | "NAVER";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 탈퇴 처리 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 인증되지 않은 요청 (UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "인증이 필요합니다"
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 이미 탈퇴 처리된 계정 (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "message": "이미 탈퇴 처리된 소셜 계정입니다."
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
